# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Setting

# Model Form Field configuration
form: $/alekseyp/multisite/models/setting/fields.yaml

# Model Class name
modelClass: Alekseyp\Multisite\Models\Setting

# Default redirect location
defaultRedirect: alekseyp/multisite/settings

# Create page
create:
    title: alekseyp.multisite::lang.controller.create
    redirect: alekseyp/multisite/settings/update/:id
    redirectClose: alekseyp/multisite/settings

# Update page
update:
    title: alekseyp.multisite::lang.controller.create
    redirect: alekseyp/multisite/settings
    redirectClose: alekseyp/multisite/settings
